before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - npm install -g bower
  - bower install -f

language: node_js
node_js:
  - stable
